name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
    
    - name: use freebsd
      id: test
      uses: vmactions/freebsd-vm@v0
      with:
        usesh: true
        
        run: |
          make update
          make dvd
          make print-IMAGESDIR
      

