name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
    
    - name: use freebsd
      id: test
      uses: vmactions/freebsd-vm@v0
      with:
        usesh: true
        mem: 4096
        prepare: |
          pkg install -y git
        run: |
          env ROOTDIR=/Users/runner/work/tools make update
          make dvd
          make print-IMAGESDIR
      

